# Use root/example as user/password credentials
version: '3.1'

services:
  
  app:
    build:
      context: ./nodejs-mysql
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
      image: mysql
      restart: "no"
      ports: 
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: kunal123
        MYSQL_DATABASE: kunal_demo
      
      healthcheck: 
        test: ["CMD-SHELL", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=kunal123"]
        interval: 5s
        retries: 5
        timeout: 3s

volumes:
  db_data:
